version: "3.8"
services:
  node:
    image: "node:16"
    env_file:
      - .env.local
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    # command: "npm start"
